spring:
  profiles:
    include: oauth

  redis:
    host: localhost # redis 설정
    port: 6379



  datasource:
    jpa:
      hibernate:
        ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true